// Code generated by protoc-gen-go.
// source: rce.proto
// DO NOT EDIT!

/*
Package rce is a generated protocol buffer package.

It is generated from these files:
	rce.proto

It has these top-level messages:
	Empty
	Status
	ID
	Command
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type STATE int32

const (
	STATE_UNKNOWN  STATE = 0
	STATE_PENDING  STATE = 1
	STATE_RUNNING  STATE = 2
	STATE_COMPLETE STATE = 3
	STATE_FAIL     STATE = 4
	STATE_TIMEOUT  STATE = 5
	STATE_STOPPED  STATE = 6
)

var STATE_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETE",
	4: "FAIL",
	5: "TIMEOUT",
	6: "STOPPED",
}
var STATE_value = map[string]int32{
	"UNKNOWN":  0,
	"PENDING":  1,
	"RUNNING":  2,
	"COMPLETE": 3,
	"FAIL":     4,
	"TIMEOUT":  5,
	"STOPPED":  6,
}

func (x STATE) String() string {
	return proto.EnumName(STATE_name, int32(x))
}
func (STATE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	ID        string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	State     STATE    `protobuf:"varint,3,opt,name=State,enum=rce.STATE" json:"State,omitempty"`
	PID       int64    `protobuf:"varint,4,opt,name=PID" json:"PID,omitempty"`
	StartTime int64    `protobuf:"varint,5,opt,name=StartTime" json:"StartTime,omitempty"`
	StopTime  int64    `protobuf:"varint,6,opt,name=StopTime" json:"StopTime,omitempty"`
	ExitCode  int64    `protobuf:"varint,7,opt,name=ExitCode" json:"ExitCode,omitempty"`
	Args      []string `protobuf:"bytes,8,rep,name=Args" json:"Args,omitempty"`
	Stdout    []string `protobuf:"bytes,9,rep,name=Stdout" json:"Stdout,omitempty"`
	Stderr    []string `protobuf:"bytes,10,rep,name=Stderr" json:"Stderr,omitempty"`
	Error     string   `protobuf:"bytes,11,opt,name=Error" json:"Error,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Status) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Status) GetState() STATE {
	if m != nil {
		return m.State
	}
	return STATE_UNKNOWN
}

func (m *Status) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *Status) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Status) GetStopTime() int64 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

func (m *Status) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Status) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Status) GetStdout() []string {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *Status) GetStderr() []string {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ID struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Command struct {
	Name      string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Arguments []string `protobuf:"bytes,2,rep,name=Arguments" json:"Arguments,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "rce.Empty")
	proto.RegisterType((*Status)(nil), "rce.Status")
	proto.RegisterType((*ID)(nil), "rce.ID")
	proto.RegisterType((*Command)(nil), "rce.Command")
	proto.RegisterEnum("rce.STATE", STATE_name, STATE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RCEAgent service

type RCEAgentClient interface {
	// Start a command and immediately return its ID. Be sure to call Wait or Stop
	// to reap the command, else the agent will effectively leak memory by holding
	// unreaped commands. A command is considered running until reaped.
	Start(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ID, error)
	// Wait for a command to complete or be stopped, reap it, and return its final status.
	Wait(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error)
	// Get the status of a command if it hasn't been reaped by calling Wait or Stop.
	GetStatus(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error)
	// Stop then reap a command by sending it a SIGTERM signal.
	Stop(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error)
	// Return a list of all running (not reaped) commands by ID.
	Running(ctx context.Context, in *Empty, opts ...grpc.CallOption) (RCEAgent_RunningClient, error)
}

type rCEAgentClient struct {
	cc *grpc.ClientConn
}

func NewRCEAgentClient(cc *grpc.ClientConn) RCEAgentClient {
	return &rCEAgentClient{cc}
}

func (c *rCEAgentClient) Start(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := grpc.Invoke(ctx, "/rce.RCEAgent/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCEAgentClient) Wait(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/rce.RCEAgent/Wait", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCEAgentClient) GetStatus(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/rce.RCEAgent/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCEAgentClient) Stop(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/rce.RCEAgent/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCEAgentClient) Running(ctx context.Context, in *Empty, opts ...grpc.CallOption) (RCEAgent_RunningClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RCEAgent_serviceDesc.Streams[0], c.cc, "/rce.RCEAgent/Running", opts...)
	if err != nil {
		return nil, err
	}
	x := &rCEAgentRunningClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RCEAgent_RunningClient interface {
	Recv() (*ID, error)
	grpc.ClientStream
}

type rCEAgentRunningClient struct {
	grpc.ClientStream
}

func (x *rCEAgentRunningClient) Recv() (*ID, error) {
	m := new(ID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RCEAgent service

type RCEAgentServer interface {
	// Start a command and immediately return its ID. Be sure to call Wait or Stop
	// to reap the command, else the agent will effectively leak memory by holding
	// unreaped commands. A command is considered running until reaped.
	Start(context.Context, *Command) (*ID, error)
	// Wait for a command to complete or be stopped, reap it, and return its final status.
	Wait(context.Context, *ID) (*Status, error)
	// Get the status of a command if it hasn't been reaped by calling Wait or Stop.
	GetStatus(context.Context, *ID) (*Status, error)
	// Stop then reap a command by sending it a SIGTERM signal.
	Stop(context.Context, *ID) (*Status, error)
	// Return a list of all running (not reaped) commands by ID.
	Running(*Empty, RCEAgent_RunningServer) error
}

func RegisterRCEAgentServer(s *grpc.Server, srv RCEAgentServer) {
	s.RegisterService(&_RCEAgent_serviceDesc, srv)
}

func _RCEAgent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCEAgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rce.RCEAgent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCEAgentServer).Start(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCEAgent_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCEAgentServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rce.RCEAgent/Wait",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCEAgentServer).Wait(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCEAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCEAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rce.RCEAgent/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCEAgentServer).GetStatus(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCEAgent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCEAgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rce.RCEAgent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCEAgentServer).Stop(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCEAgent_Running_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RCEAgentServer).Running(m, &rCEAgentRunningServer{stream})
}

type RCEAgent_RunningServer interface {
	Send(*ID) error
	grpc.ServerStream
}

type rCEAgentRunningServer struct {
	grpc.ServerStream
}

func (x *rCEAgentRunningServer) Send(m *ID) error {
	return x.ServerStream.SendMsg(m)
}

var _RCEAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rce.RCEAgent",
	HandlerType: (*RCEAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _RCEAgent_Start_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _RCEAgent_Wait_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RCEAgent_GetStatus_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _RCEAgent_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Running",
			Handler:       _RCEAgent_Running_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rce.proto",
}

func init() { proto.RegisterFile("rce.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xbd, 0xfa, 0x63, 0x49, 0xe3, 0x10, 0xc4, 0x10, 0xca, 0x62, 0x42, 0x10, 0xea, 0xc5,
	0xf4, 0x10, 0x4a, 0x7a, 0xec, 0x49, 0x58, 0xdb, 0x20, 0x9a, 0xac, 0x85, 0x24, 0x93, 0x6b, 0xd5,
	0x78, 0x11, 0x3a, 0x48, 0x32, 0xeb, 0x15, 0xb4, 0x6f, 0xd1, 0x97, 0xe9, 0xfb, 0x95, 0x5d, 0x29,
	0x4e, 0x28, 0xe4, 0x36, 0xbf, 0xef, 0x1b, 0xa4, 0xd9, 0x99, 0x0f, 0x02, 0xf9, 0x2c, 0x6e, 0x8f,
	0x72, 0x50, 0x03, 0xda, 0xf2, 0x59, 0xc4, 0x1e, 0xb8, 0xac, 0x3b, 0xaa, 0xdf, 0xf1, 0x1f, 0x0b,
	0x96, 0xa5, 0xaa, 0xd5, 0x78, 0xc2, 0x4b, 0xb0, 0xb2, 0x94, 0x92, 0x88, 0x6c, 0x82, 0xc2, 0xca,
	0x52, 0x44, 0x70, 0x78, 0xdd, 0x09, 0x6a, 0x19, 0xc5, 0xd4, 0x18, 0x81, 0xab, 0xbb, 0x05, 0xb5,
	0x23, 0xb2, 0xb9, 0xbc, 0x83, 0x5b, 0xfd, 0xdd, 0xb2, 0x4a, 0x2a, 0x56, 0x4c, 0x06, 0x86, 0x60,
	0xe7, 0x59, 0x4a, 0x9d, 0x88, 0x6c, 0xec, 0x42, 0x97, 0x78, 0x0d, 0x41, 0xa9, 0x6a, 0xa9, 0xaa,
	0xb6, 0x13, 0xd4, 0x35, 0xfa, 0xab, 0x80, 0x6b, 0xf0, 0x4b, 0x35, 0x1c, 0x8d, 0xb9, 0x34, 0xe6,
	0x99, 0xb5, 0xc7, 0x7e, 0xb5, 0x6a, 0x3b, 0x1c, 0x04, 0xf5, 0x26, 0xef, 0x85, 0xf5, 0x74, 0x89,
	0x6c, 0x4e, 0xd4, 0x8f, 0x6c, 0x3d, 0x9d, 0xae, 0xf1, 0x83, 0x7e, 0xcb, 0x61, 0x18, 0x15, 0x0d,
	0x8c, 0x3a, 0xd3, 0xac, 0x0b, 0x29, 0x29, 0x9c, 0x75, 0x21, 0x25, 0x5e, 0x81, 0xcb, 0xa4, 0x1c,
	0x24, 0x5d, 0x99, 0x27, 0x4e, 0x10, 0x5f, 0xe9, 0x3d, 0xfc, 0xbf, 0x8d, 0xf8, 0x2b, 0x78, 0xdb,
	0xa1, 0xeb, 0xea, 0xfe, 0x70, 0x5e, 0x0c, 0x79, 0xb3, 0x98, 0x6b, 0x08, 0x12, 0xd9, 0x8c, 0x9d,
	0xe8, 0xd5, 0x89, 0x5a, 0xe6, 0x2f, 0xaf, 0xc2, 0xa7, 0x1f, 0xe0, 0x9a, 0x25, 0xe1, 0x0a, 0xbc,
	0x3d, 0xff, 0xce, 0x77, 0x4f, 0x3c, 0x5c, 0x68, 0xc8, 0x19, 0x4f, 0x33, 0x7e, 0x1f, 0x12, 0x0d,
	0xc5, 0x9e, 0x73, 0x0d, 0x16, 0x5e, 0x80, 0xbf, 0xdd, 0x3d, 0xe6, 0x0f, 0xac, 0x62, 0xa1, 0x8d,
	0x3e, 0x38, 0xdf, 0x92, 0xec, 0x21, 0x74, 0x74, 0x53, 0x95, 0x3d, 0xb2, 0xdd, 0xbe, 0x0a, 0x5d,
	0x0d, 0x65, 0xb5, 0xcb, 0x73, 0x96, 0x86, 0xcb, 0xbb, 0xbf, 0x04, 0xfc, 0x62, 0xcb, 0x92, 0x46,
	0xf4, 0x6a, 0xbe, 0x92, 0x54, 0x78, 0x61, 0xee, 0x33, 0xcf, 0xbd, 0xf6, 0x0c, 0x65, 0x69, 0xbc,
	0xc0, 0x1b, 0x70, 0x9e, 0xea, 0x56, 0xe1, 0x8b, 0xb4, 0x5e, 0x4d, 0x97, 0x34, 0x49, 0x88, 0x17,
	0xf8, 0x11, 0x82, 0x7b, 0xa1, 0xe6, 0x60, 0xbc, 0xd7, 0x74, 0x03, 0x8e, 0x3e, 0xd5, 0xbb, 0x7e,
	0x0c, 0x5e, 0x31, 0xf6, 0x7d, 0xdb, 0x37, 0x38, 0x05, 0xc5, 0x44, 0xee, 0xcd, 0x18, 0x9f, 0xc9,
	0xcf, 0xa5, 0x09, 0xe5, 0x97, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x05, 0xa2, 0xb3, 0xa1,
	0x02, 0x00, 0x00,
}
